name: CI

on:
  push:
    branches-ignore: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install modules
        run: yarn install
        continue-on-error: false

      - name: run tests
        run: yarn jest
        continue-on-error: false
